# Generated by Django 4.1 on 2022-08-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
